name: SRT_AI  
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9 
  - tensorflow
  - scipy
  - scikit-image
  - pillow  
  - scikit-learn
  - seaborn
  - pip  
  - pip:
      - bruges
