name: SRT_AI
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - tensorflow=2.9.1
  - scipy
  - scikit-image
  - pillow
  - scikit-learn
  - seaborn
  - pip
  - pip:
      - bruges
